#!/usr/bin/python3

import rospy
import torch
from std_msgs.msg import String


def main():
    # (ROS node init) trpo_stage_1
    node_name = "is_cuda"
    rospy.init_node(node_name, anonymous=True)
    # (ROS print) torch.cuda.is_available()
    # pub_cuda = rospy.Publisher("cuda_device", String, queue_size=10)
    rospy.loginfo("CUDA_TOOLKIT: %s", torch.cuda.is_available())


if __name__ == "__main__":
    main()
